### ISSUE TITLE
Video Problem

### ISSUE THREAD

**Issue by Git-Hoon** [reasonset/qtabwebview#1]
There is something wrong with the browser. I can not watch Streaming Media through it. Media platform remains me that my browser version is too low.

**Comment by reasonset** [comment]
I'm also aware that the problem exists.
However, since the problem is caused by Qt5 WebEngine, it cannot be solved by this application. The same problem should occur with other web browsers that use the Qt5 WebEngine (e.g. Otter Browser).

Please let us know if there are any other browsers that use the Qt5 WebEngine that do not have the same problem.
